### PR TITLE
#132 css verification and cleanup

### PR DESCRIPTION
**Pull request by erikajansson1**
#### What does this PR do?
CSS and Icon fixes.
[Issue](#132 #131 )

##### Why are we doing this? Any context or related work?
To create a better user experience.
#### Where should a reviewer start?
Where ever he wants. 
#### Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).
Do not close the issues, I'll continue working on them but due to risk of huge merge conflicts I'll "push" this now.

### CODE REVIEW

**Comment by jakobemilandersson** [comment]
I have not been able to test to see if all functionality is still intact but it seems so! Everything looks great on my Nexus 5X emulator except for this:
bild
The 'upload'-circle is displayed over the profile picture. I'm not sure if that is intended or not 😄 

Will be taking a look on the SignUp, Login, and ResetPasswords screens now and then try everything out on my Galaxy A5 (my real phone)!

**Comment by jakobemilandersson** [comment]
Should the buttons in the SignUp, LogIn and ResetPassword screen have the same style as e.g. Profile? 😄

**Comment by jakobemilandersson** [comment]
bild
The error text for ResetPassword is now hidden behind the button! (Thanks @lucatonile for finding this)

**Comment by jakobemilandersson** [comment]
bild
bild

The '+' profile picture button is hidden on my Galaxy A5 as well and the icons for 'Add from album' and 'Take a photo' is kind of out of the screen on my phone as well. But my phone doesn't have the greatest resolution haha! 😄

**Comment by erikajansson1** [comment]
1. The upload profile picture icon is placed over the picture on purpose, I'm not sure how to make it look really great with the icon though, standard is to put it in the right corner somewhere there but.... Can you not see the icon or your Galaxy or is it just on top of the picture? 
2. I've changed the buttons so they have the same style, the only difference should be the shadow and the black border (and length). I can not decide if they should be the same or if they can be different, since they are nice at different places (that's why they are different at different places).
3. I completely missed the error test when I relocated the button, I fix!
4. I'll look at the add/take a photo icons, they should be in the screen....

**Comment by jakobemilandersson** [comment]
> 
> 
>     1. The upload profile picture icon is placed over the picture on purpose, I'm not sure how to make it look really great with the icon though, standard is to put it in the right corner somewhere there but.... Can you not see the icon or your Galaxy or is it just on top of the picture?
> 
>     2. I've changed the buttons so they have the same style, the only difference should be the shadow and the black border (and length). I can not decide if they should be the same or if they can be different, since they are nice at different places (that's why they are different at different places).
> 
>     3. I completely missed the error test when I relocated the button, I fix!
> 
>     4. I'll look at the add/take a photo icons, they should be in the screen....

1. Okey cool, wasn't sure if it was intended or not. The different pictures I posted are from the emulator and my real phone and the icon is visible on both, not sure I understand your question 😄 
4. Yeah, probably just my real phone being a little tricky haha. But it looks great on my emulator! 😃 

I think that the design looks really good and sleek, great job! 😸

**Review by jakobemilandersson — DISMISSED** [review]
😸

**Review by jakobemilandersson — APPROVED** [review]
😸 2.0

**Pull request merged**
