### PR TITLE
Fixed gamification screen to work on Android phones to. Also fixed pr…

### LINKED ISSUE #103: Gamifaction.js is not rendering correctly on Android
Only the Flatlist for Local-toplist is rendering and only two items are visible. The FlatList doesn't respond on drag aswell as the parent Scrollview!
This was found on a Nexus 5X emulator!

### PR DESCRIPTION
**Pull request by erikajansson1**
…ofile pictures that had stopped working due to DB changes

#### What does this PR do?
Fixed gamification screen to work on Android phones to. Also fixed pr ofile pictures that had stopped working due to DB changes.
[Issue](#103 )

##### Why are we doing this? Any context or related work?
So the application works for everyone and to fix what was broken.
#### Where should a reviewer start?
Gamification.js
#### Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).
closes #103

### CODE REVIEW

**Comment by jakobemilandersson** [comment]
I'm unable to access either 'profile' or 'game' using the footer, getting this error;
bild

Tried creating a new user but still got the error. 😿

**Comment by jakobemilandersson** [comment]
> 
> 
> I'm unable to access either 'profile' or 'game' using the footer, getting this error;
> bild
> 
> Tried creating a new user but still got the error. 😿

This is what the log says, seems like avatarUri is still of type 'String' instead of an Object
bild

**Review by FredSoderberg — DISMISSED** [review]
except the bug where the profile image upload is taking forever now with thumbnails on the server side everything seems to work

**Review by FredSoderberg — APPROVED** [review]

**Comment by FredSoderberg** [comment]
God job!

**Pull request merged**
