### PR TITLE
#125 thumb counter

### LINKED ISSUE #125: implement visible counter on comments thumbs up/down
Count number of comment thumbs up / down and visualize that as a number on their respective thumb icon in the bike comment.

### PR DESCRIPTION
**Pull request by erikajansson1**
#### What does this PR do?
Adds a counter based on how many thumbs up/down a comment has received.
[Issue](#125 )

##### Why are we doing this? Any context or related work?
So users can vote on comments and see what comments is "good" and which ones are bad.
#### Where should a reviewer start?
Comment.js
#### Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).
closes #125

### CODE REVIEW

**Comment by jakobemilandersson** [comment]
By making two thumbs up (or thumbs down) on two different comments results in weird behaviour (as stated in the Slack-channel) but the second action console logs *JSON Parse error: Unexpected identifier "up"* on the client.

I will wait until the back-end team has found the error that causes this before I continue with the review, doesn't feel like the right time for it now!

**Comment by FredSoderberg** [comment]
the 'up' is part of their message when they remove 'up vote' or 'down vote'. ignore JSON parse errors until backend have gotten the error msg uniformed.
The json parse errors should though be fixed with latest PR

**Comment by FredSoderberg** [comment]
after much testing I can verify that we don't send "hidden" calls and that the bug is on the server side

**Review by FredSoderberg — APPROVED** [review]
very nice refresh and good job, hopefully this will work better when back end fixes this weird bug

**Pull request merged**
