### PR TITLE
#116 min password

### LINKED ISSUE #116: implement minimum password rules
easiest done on the client side probalby

### PR DESCRIPTION
**Pull request by jakobemilandersson**
#### What does this PR do?
Implements a strength-requirement on the selected password when creating a new user!
The requirements are:

- Needs to be atleast 8 characters.
- Atleast one character has to be lowercase.
- Atleast one character has to be uppercase.
- Atleast one character has to be a number.
- Atleast one character has to be a special character.

Also removes a promise-warning when using the preadd function (fixed so that all keys are correctly named/used).
[Issue](LINK_TO_ISSUE)
#116 
##### Why are we doing this? Any context or related work?
To increase user-information security!
#### Where should a reviewer start?
SignUp.js
#### Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).
closes #116

### CODE REVIEW

**Review by adrian621 — COMMENTED** [review]
password check verkar funkafunkar 👍 

Får dock 

[09:57:13] null is not an object (evaluating 'responseJson.data.token')
* screens/SignUp.js:133:16 in <unknown>
- node_modules/promise/setimmediate/core.js:37:14 in tryCallOne
- node_modules/promise/setimmediate/core.js:123:25 in <unknown>
- ... 8 more stack frames from framework internals

Om jag försöker registrera användare som redan finns? Eller ibland? Testa:

namn: A
email: A@a.a
phone: 
pass: Aa1?1234
Pass2: Aa1?1234

**Review by adrian621 — APPROVED** [review]
Approve?

**Review by adrian621 — CHANGES_REQUESTED** [review]
unapprove

**Comment by jakobemilandersson** [comment]
Okej! Tror det är något som har missats att testas tidigare så fixar det, good catch! 😄

**Comment by jakobemilandersson** [comment]
> 
> 
> Okej! Tror det är något som har missats att testas tidigare så fixar det, good catch! 😄

Commit 1e66667 should fixed this! 😃

**Review by adrian621 — APPROVED** [review]

**Pull request merged**
