### PR TITLE
Fixed icon bug with a "hack"

### LINKED ISSUE #195: Map has no marker (Adrians phone)

### PR DESCRIPTION
**Pull request by FredSoderberg**
#### What does this PR do?
Bug fix, a well known problem on android (google maps) is that image children isn't rendered correctly. So we solved this by using a hack, simply overlaying a image over the map view
[#195](LINK_TO_ISSUE)

##### Why are we doing this? Any context or related work?
to include adrians phone
#### Where should a reviewer start?
pinmap.js
#### Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).
closes #195

### CODE REVIEW

**Review by jakobemilandersson — DISMISSED** [review]
The marker is visible on my Galaxy A5 now!
But trying to set a location when the "Last known location of your lost bike:" are empty (both City and Street are empty) the screen gets stuck in "Loading", not sure what is happening 😢

**Review by adrian621 — COMMENTED** [review]
Getting "Failed prop type" mapState.city (its value is null) when hovering over some positions on the map

**Comment by FredSoderberg** [comment]
@adrianTyrevall stop losing bikes in the wilderness or places that doesn't have postal och street names then :P 
guarded for null values now

**Review by adrian621 — APPROVED** [review]

**Review by jakobemilandersson — APPROVED** [review]
The Bikeinie (or Cykelinspektionen?) marker is displaying nicely for me and hasn't gotten any City-problems! 😄

**Pull request merged**
